version: 2.0

jobs:
 one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first build in CircleCI"
      - run: sleep 10
 two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A second hello"
      - run: sleep 15
      
workflows: 
  version: 2
    jobs: 
      - one
      - two
